import React, { useState } from 'react'
import bag1 from "../../../../../public/bag1.webp"
import bag2 from "../../../../../public/bag2.webp"
import bag3 from "../../../../../public/bag3.webp"
import bag4 from "../../../../../public/bag4.webp"
import bag5 from "../../../../../public/bag5.webp"
import bag6 from "../../../../../public/bag6.webp"
import bag7 from "../../../../../public/bag7.webp"
import bag8 from "../../../../../public/bag8.webp"
import bagHover1 from "../../../../../public/bagg1.webp"
import bagHover2 from "../../../../../public/bagg2.webp"
import bagHover3 from "../../../../../public/bagg3.webp"
import bagHover4 from "../../../../../public/bagg4.webp"
import bagHover5 from "../../../../../public/bagg5.webp"
import bagHover6 from "../../../../../public/bagg6.webp"
import bagHover7 from "../../../../../public/bagg7.webp"
import bagHover8 from "../../../../../public/bagg8.webp"
import allProductBg from '../../../../../public/allProductBg.webp'
import Card from '../../../Component/Card/Card'
import { Grid3x3GapFill, GridFill } from 'react-bootstrap-icons'

const commonData = [
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
    {
        id: 1,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1829,
        image: bag1,
        HoverImage: bagHover1,
        old_price: 2899,
        rating: 4,
        discount: "37%",
    },
    {
        id: 2,
        title: "Accelerator",
        category: "Bag",
        price: 1599,
        image: bag2,
        HoverImage: bagHover2,
        old_price: 2399,
        rating: 5,
        discount: "33%",
    },
    {
        id: 3,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag3,
        HoverImage: bagHover3,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 4,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag4,
        HoverImage: bagHover4,
        old_price: 3299,
        rating: 4,
        discount: "42%",
    },
    {
        id: 5,
        title: "Armor Dust / Rain Cover for Backpack",
        category: "Bag",
        price: 449,
        image: bag5,
        HoverImage: bagHover5,
        old_price: 499,
        rating: 5,
        discount: "10%",
    },
    {
        id: 6,
        title: "Amigo Backpack",
        category: "Bag",
        price: 1899,
        image: bag6,
        HoverImage: bagHover6,
        old_price: 3299,
        rating: 5,
        discount: "42%",
    },
    {
        id: 7,
        title: "Fitpack Neo",
        category: "Bag",
        price: 1899,
        image: bag7,
        HoverImage: bagHover7,
        old_price: 2899,
        rating: 5,
        discount: "37%",
    },
    {
        id: 8,
        title: "Caprio",
        category: "Bag",
        price: 999,
        image: bag8,
        HoverImage: bagHover8,
        old_price: 1999,
        rating: 5,
        discount: "50%",
    },
]

export default function CommonProduct() {
    let [gridCols, setGridCols] = useState("grid grid-cols-3")

    return (
        <>
            <img src={allProductBg} alt="" />
            <div className='container-fluid'>
                <h1 className='text-center text-2xl mt-5 m-0'>All Products</h1>
                <div className='flex justify-end items-center gap-2.5 pr-5 my-5 text-[#777777] [&_svg]:!cursor-pointer'>
                    <GridFill className='hover:!text-[#191919]' onClick={() => setGridCols("grid grid-cols-2")} />
                    <Grid3x3GapFill className='hover:!text-[#191919]' onClick={() => setGridCols("grid grid-cols-3")} />
                    <div className='flex text-[#777777] hover:text-[#191919] text-[8px]' onClick={() => setGridCols("grid grid-cols-4")}>
                        <div>
                            <GridFill />
                            <GridFill />
                        </div>
                        <div>
                            <GridFill />
                            <GridFill />
                        </div>
                    </div>
                </div>
                <div className={gridCols}>
                    {
                        commonData?.map((item, index) => (
                            <Card key={index} data={item} />
                        ))
                    }
                </div>
            </div>
        </>
    )
}


// import React, { useEffect, useState } from 'react'
// import allProductBg from '../../../../../public/allProductBg.webp'
// import Card from '../../../Component/Card/Card'
// import { Grid3x3GapFill, GridFill } from 'react-bootstrap-icons'
// import axios from 'axios'
// import { BE_URL } from '../../../../Config'

// export default function CommonProduct() {
//     let [gridCols, setGridCols] = useState("grid grid-cols-3")
//     let [commonProduct, setCommonProduct] = useState([])

//     useEffect(() => {
//         axios({
//             method: "get",
//             url: BE_URL + '/product/getAll',
//         })?.then((res) => {
//             console.log("------res--->", res?.data?.data)
//             setCommonProduct(res?.data?.data)
//         })?.catch((err) => {
//             console.log(err)
//         })
//     }, [])

//     return (
//         <>
//             <img src={allProductBg} alt="" />
//             <div className='container-fluid'>
//                 <h1 className='text-center text-2xl mt-5 m-0'>All Products</h1>
//                 <div className='flex justify-end items-center gap-2.5 pr-5 my-5 text-[#777777] [&_svg]:!cursor-pointer'>
//                     <GridFill className='hover:!text-[#191919]' onClick={() => setGridCols("grid grid-cols-2")} />
//                     <Grid3x3GapFill className='hover:!text-[#191919]' onClick={() => setGridCols("grid grid-cols-3")} />
//                     <div className='flex text-[#777777] hover:text-[#191919] text-[8px]' onClick={() => setGridCols("grid grid-cols-4")}>
//                         <div>
//                             <GridFill />
//                             <GridFill />
//                         </div>
//                         <div>
//                             <GridFill />
//                             <GridFill />
//                         </div>
//                     </div>
//                 </div>
//                 <div className={gridCols}>
//                     {
//                         commonProduct?.map((item, index) => {
//                             return <Card key={index} data={item} />
//                         })
//                     }
//                 </div>
//             </div>
//         </>
//     )
// }
